#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AHORCADOGAME.Resource", IsApplication=true)]

namespace AHORCADOGAME
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ElHG = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int oeste1 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int oeste2 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int oeste3 = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000f
			public const int btnA = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int btnB = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int btnC = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int btnD = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int btnE = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int btnF = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int btnG = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int btnH = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int btnI = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int btnJ = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int btnK = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int btnL = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int btnM = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int btnN = 2131034140;
			
			// aapt resource value: 0x7f05001e
			public const int btnO = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int btnP = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int btnQ = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int btnR = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int btnS = 2131034146;
			
			// aapt resource value: 0x7f05000c
			public const int btnStart = 2131034124;
			
			// aapt resource value: 0x7f050023
			public const int btnT = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int btnU = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int btnV = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int btnW = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int btnX = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int btnY = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int btnZ = 2131034153;
			
			// aapt resource value: 0x7f050004
			public const int btn_aceptarinst = 2131034116;
			
			// aapt resource value: 0x7f05002c
			public const int btn_captura = 2131034156;
			
			// aapt resource value: 0x7f050002
			public const int btn_credito = 2131034114;
			
			// aapt resource value: 0x7f050037
			public const int btn_creditos = 2131034167;
			
			// aapt resource value: 0x7f05002f
			public const int btn_empezar = 2131034159;
			
			// aapt resource value: 0x7f050034
			public const int btn_instrucciones = 2131034164;
			
			// aapt resource value: 0x7f050032
			public const int btn_jugar = 2131034162;
			
			// aapt resource value: 0x7f050035
			public const int btn_palabras = 2131034165;
			
			// aapt resource value: 0x7f050030
			public const int btn_salir = 2131034160;
			
			// aapt resource value: 0x7f05001d
			public const int btnÑ = 2131034141;
			
			// aapt resource value: 0x7f05000b
			public const int cronometro = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public const int gridLayout_Teclado = 2131034126;
			
			// aapt resource value: 0x7f050008
			public const int imageView1 = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int imgTitulo = 2131034115;
			
			// aapt resource value: 0x7f050031
			public const int lblNombre = 2131034161;
			
			// aapt resource value: 0x7f05000d
			public const int lblPalabraOculta = 2131034125;
			
			// aapt resource value: 0x7f050038
			public const int lblVerListas = 2131034168;
			
			// aapt resource value: 0x7f05000a
			public const int lbl_Nombre = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int linearLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int linearLayout2 = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int linearLayout3 = 2131034121;
			
			// aapt resource value: 0x7f05003a
			public const int listView1 = 2131034170;
			
			// aapt resource value: 0x7f050039
			public const int spnCategorias = 2131034169;
			
			// aapt resource value: 0x7f050005
			public const int tableLayout1 = 2131034117;
			
			// aapt resource value: 0x7f05002e
			public const int tableRow1 = 2131034158;
			
			// aapt resource value: 0x7f050006
			public const int tableRow2 = 2131034118;
			
			// aapt resource value: 0x7f050033
			public const int tableRow3 = 2131034163;
			
			// aapt resource value: 0x7f050036
			public const int tableRow4 = 2131034166;
			
			// aapt resource value: 0x7f05002d
			public const int textView000 = 2131034157;
			
			// aapt resource value: 0x7f050001
			public const int textView1 = 2131034113;
			
			// aapt resource value: 0x7f05002b
			public const int textView2 = 2131034155;
			
			// aapt resource value: 0x7f05002a
			public const int txtNombre = 2131034154;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int creditos = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int instrucciones = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int juego = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MENU = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int palabras = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
