#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AHORCADOGAME.Resource", IsApplication=true)]

namespace AHORCADOGAME
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int ED_txtNombre = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int btn_aceptarinst = 2131034115;
			
			// aapt resource value: 0x7f050015
			public const int btn_aceptarpala = 2131034133;
			
			// aapt resource value: 0x7f050008
			public const int btn_captura = 2131034120;
			
			// aapt resource value: 0x7f050002
			public const int btn_credito = 2131034114;
			
			// aapt resource value: 0x7f050014
			public const int btn_creditos = 2131034132;
			
			// aapt resource value: 0x7f05000c
			public const int btn_empezar = 2131034124;
			
			// aapt resource value: 0x7f050010
			public const int btn_instrucciones = 2131034128;
			
			// aapt resource value: 0x7f05000e
			public const int btn_jugar = 2131034126;
			
			// aapt resource value: 0x7f050012
			public const int btn_palabras = 2131034130;
			
			// aapt resource value: 0x7f05000d
			public const int btn_salir = 2131034125;
			
			// aapt resource value: 0x7f050000
			public const int linearLayout1 = 2131034112;
			
			// aapt resource value: 0x7f05000a
			public const int tableLayout1 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int tableRow1 = 2131034123;
			
			// aapt resource value: 0x7f050011
			public const int tableRow2 = 2131034129;
			
			// aapt resource value: 0x7f05000f
			public const int tableRow3 = 2131034127;
			
			// aapt resource value: 0x7f050013
			public const int tableRow4 = 2131034131;
			
			// aapt resource value: 0x7f050004
			public const int textView0 = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int textView00 = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int textView000 = 2131034121;
			
			// aapt resource value: 0x7f050001
			public const int textView1 = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int textView2 = 2131034119;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int creditos = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int instrucciones = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MENU = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int palabras = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
